### ISSUE TITLE
Dependency Error With Entity Framework

### ISSUE THREAD

**Issue by cevarief** [aspnet/cli-samples#47] opened 2016-04-24 00:45 UTC
I create a project base on HelloMVC and add ```"Microsoft.EntityFrameworkCore.Sqlite": "1.0.0-*"```. It shows a bunch of incompatibility dependencies when restoring the packages. Any work around ?

```bash
Errors in ~/Development/aspnet/HelloMVC2/project.json
    Package Ix-Async 1.2.5 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Ix-Async 1.2.5 supports:
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile78)
    Package Remotion.Linq 2.0.2 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Remotion.Linq 2.0.2 supports:
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

NuGet Config files used:
    ~/Development/aspnet/HelloMVC2/NuGet.Config
    ~/.nuget/NuGet/NuGet.Config

Feeds used:
    https://www.myget.org/F/aspnetcirelease/api/v3/index.json
    https://api.nuget.org/v3/index.json
```
Dotnet Info : 
```bash
.NET Command Line Tools (1.0.0-rc2-002485)

Product Information:
 Version:     1.0.0-rc2-002485
 Commit Sha:  d3c65aee87

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by moozzyk** [comment] 2016-04-25 16:53
@divega - do you just add imports to the portable tfms (I don't see any dnxcore50 tfms) to make it work? Or how do you fix that?

**Comment by GuardRex** [comment] 2016-04-25 17:19
Maybe this will work ...
```json
"frameworks": {
    "netcoreapp1.0": {
        "imports": [ "portable-net45+win8+wp8+wpa81", "portable-net45+win8+wp8" ]
    }
},
```

**Comment by divega** [comment] 2016-04-25 18:17
@moozzyk Not sure. I saw you already raised the lack of "dnxcore50" on https://github.com/aspnet/EntityFramework/issues/3925#issuecomment-214045394. @natemcmaster any thoughts?

**Comment by natemcmaster** [comment] 2016-04-25 18:30
`"imports": "portable-net452+win81"` You need to have at least net451 in your imports because EntityFramework targets at minimum .NET 4.5.1.

This is a duplicate of https://github.com/aspnet/EntityFramework/issues/5152

**Comment by divega** [comment] 2016-04-25 18:58
Thanks @natemcmaster. aspnet/EntityFramework#5152 is actually closed. Do we have on active bug to follow up with the Ix-Async and Remotion.Linq owners to remove the need for the imports.

**Comment by natemcmaster** [comment] 2016-04-25 21:58
- https://github.com/Reactive-Extensions/Rx.NET/issues/174
- https://www.re-motion.org/jira/browse/RMLNQ-98

**Closed** 2016-04-26 17:15 UTC
